- src/main/java/com/cloudbees/groovy/cps/impl/VariableDeclBlock.java
- src/test/java/com/cloudbees/groovy/cps/TestVariableDeclaration.java
Default primitive values for float and double, plus some tests
> Add default variable assignment values for float and double, plus tests

- pom.xml
> Update Groovy to 1.8.9 to match Jenkins core

- pom.xml
@reviewbybees in preparation for a release of 1.2.
> Update parent POM to the latest.

- src/test/groovy/com/cloudbees/groovy/cps/CpsTransformerTest.groovy
> Missing @Test annotation

- src/main/groovy/com/cloudbees/groovy/cps/CpsTransformer.groovy
- src/main/java/com/cloudbees/groovy/cps/Builder.java
- src/main/java/com/cloudbees/groovy/cps/impl/ArrayAccessBlock.java
- src/main/java/com/cloudbees/groovy/cps/impl/AttributeAccessBlock.java
- src/main/java/com/cloudbees/groovy/cps/impl/ContinuationGroup.java
- src/main/java/com/cloudbees/groovy/cps/impl/FunctionCallBlock.java
- src/main/java/com/cloudbees/groovy/cps/impl/PropertyAccessBlock.java
- src/main/java/com/cloudbees/groovy/cps/impl/PropertyishBlock.java
- src/test/groovy/com/cloudbees/groovy/cps/CpsTransformerTest.groovy
[JENKINS-27271](https://issues.jenkins-ci.org/browse/JENKINS-27271)
@reviewbybees
> [JENKINS-27271] Implement safe navigation operator

- src/test/java/com/cloudbees/groovy/cps/VariableDeclarationTest.java
> Rename test suite to make sure it is actually run

- src/main/java/com/cloudbees/groovy/cps/impl/SourceLocation.java
For debugging https://github.com/jenkinsci/workflow-plugin/pull/249.
@reviewbybees esp. @kohsuke
> Added SourceLocation.toString override

- src/main/groovy/com/cloudbees/groovy/cps/CpsTransformer.groovy
- src/main/java/com/cloudbees/groovy/cps/Builder.java
- src/main/java/com/cloudbees/groovy/cps/impl/ClosureBlock.java
- src/main/java/com/cloudbees/groovy/cps/impl/CpsClosure.java
- src/test/groovy/com/cloudbees/groovy/cps/CpsTransformerTest.groovy
[JENKINS-28277](https://issues.jenkins-ci.org/browse/JENKINS-28277)
This issue got extra visibility in https://news.ycombinator.com/item?id=11362058
@reviewbybees
> [JENKINS-28277] NPE in CurriedClosure.<init>

- src/main/groovy/com/cloudbees/groovy/cps/CpsTransformer.groovy
- src/main/java/com/cloudbees/groovy/cps/Builder.java
- src/main/java/com/cloudbees/groovy/cps/impl/MethodPointerBlock.java
- src/test/groovy/com/cloudbees/groovy/cps/CpsTransformerTest.groovy
While I'm at #21, might as well.
@reviewbybees  in particular @jglick
> Added support for method pointers

- src/main/groovy/com/cloudbees/groovy/cps/CpsTransformer.groovy
- src/test/groovy/com/cloudbees/groovy/cps/CpsTransformerTest.groovy
They need no transformation. See issue #26 and PR #27.
This PR incorporates changes from PR #27.
@reviewbybees
> Do not touch interfaces

- src/test/groovy/com/cloudbees/groovy/cps/CpsTransformerTest.groovy
Unit test for interface declaration #26
Marked as `@NotYetImplemented` as there is no fix yet
> Add unit test for interface declaration

- README.md
- doc/block-tree.md
- doc/cps-basics.md
- doc/cps-model.md
- src/main/java/com/cloudbees/groovy/cps/Env.java
- src/main/java/com/cloudbees/groovy/cps/impl/CpsCallableInvocation.java
The session with @svanoort today gave me some ideas about how to approach the documentation of groovy-cps.
This is my first wave.
@reviewbybees
> Documentation take #1

- src/main/groovy/com/cloudbees/groovy/cps/CpsTransformer.groovy
- src/main/java/com/cloudbees/groovy/cps/WorkflowTransformed.java
This came up in the context of https://github.com/jenkinsci/workflow-cps-plugin/pull/59
> Annotate the type to indicate that the CPS transformer has visited

- src/main/groovy/com/cloudbees/groovy/cps/CpsTransformer.groovy
Complements https://github.com/jenkinsci/workflow-cps-plugin/pull/83.
@reviewbybees
> Unset fields at the end of call so we do not hold on to large retained sets

- src/test/groovy/com/cloudbees/groovy/cps/CpsTransformerTest.groovy
Marked as @NotYetImplemented
http://groovy-lang.org/semantics.html#_list_and_map_constructors
#31
> Unit test for type checked List to constructor coercion

- src/test/groovy/com/cloudbees/groovy/cps/CpsTransformerTest.groovy
Added unit test for #16
Marked as `@NotYetImplemented` since there is no fix yet
> Category unit test

- src/main/groovy/com/cloudbees/groovy/cps/CpsTransformer.groovy
[JENKINS-39719](https://issues.jenkins-ci.org/browse/JENKINS-39719)
@reviewbybees
> [JENKINS-39719] Must make CpsTransformer.iota globally unique

- src/main/groovy/com/cloudbees/groovy/cps/CpsTransformer.groovy
- src/main/java/com/cloudbees/groovy/cps/Next.java
- src/test/groovy/com/cloudbees/groovy/cps/AbstractGroovyCpsTest.groovy
- src/test/groovy/com/cloudbees/groovy/cps/CpsTransformerTest.groovy
[JENKINS-31484](https://issues.jenkins-ci.org/browse/JENKINS-31484)
@reviewbybees esp. @kohsuke
> [JENKINS-31484] Translate field accesses to AttributeAccessBlock rather than PropertyAccessBlock

- src/test/groovy/com/cloudbees/groovy/cps/CpsTransformerTest.groovy
[JENKINS-44280](https://issues.jenkins-ci.org/browse/JENKINS-44280)
See discussion on https://github.com/cloudbees/groovy-cps-dgm-builder/pull/4 for how this came up.
> [JENKINS-44280] Test for overloading methods

- lib/pom.xml
cc @reviewbybees but mainly @jglick
> Generate/attach test jars, test source jars.

- doc/sandbox.md
A bit of doc improvement to help illustrate #62
> Doc improvement

- lib/pom.xml
Had some problems with this; cleaning it up.
@reviewbybees
> Removing wagon-gitsite

- lib/pom.xml
- lib/src/test/groovy/com/cloudbees/groovy/cps/sandbox/SandboxInvokerTest.groovy
[JENKINS-46088](https://issues.jenkins-ci.org/browse/JENKINS-46088)
Downstream of https://github.com/jenkinsci/groovy-sandbox/pull/37
> [JENKINS-46088] Downstream testing of double-transformation fix

- lib/src/main/java/com/cloudbees/groovy/cps/CpsTransformer.java
- lib/src/test/groovy/com/cloudbees/groovy/cps/CpsTransformerTest.groovy
[JENKINS-44027](https://issues.jenkins-ci.org/browse/JENKINS-44027)
Still need to think about whether to move all the declaration logic into `multipleAssignment` as well, or pull some of it of `multipleAssignment` out into `visitDeclarationExpression`.
> [FIXED JENKINS-44027] Support multiple assignment

- lib/src/main/java/com/cloudbees/groovy/cps/CpsTransformer.java
- lib/src/test/groovy/com/cloudbees/groovy/cps/CpsTransformerTest.groovy
[JENKINS-32213](https://issues.jenkins-ci.org/browse/JENKINS-32213)
> [FIXED JENKINS-32213] Automatically make all CPS classes serializable

- lib/src/main/java/com/cloudbees/groovy/cps/CpsTransformer.java
- lib/src/test/groovy/com/cloudbees/groovy/cps/CpsTransformerTest.groovy
- lib/src/test/groovy/com/cloudbees/groovy/cps/sandbox/SandboxInvokerTest.groovy
[JENKINS-49679](https://issues.jenkins-ci.org/browse/JENKINS-49679)
Evaluate the RHS into a temp variable and use that instead of the original expression.
> [FIXED JENKINS-49679] Don't run RHS of multiple assignment more than once

- pom.xml
Analogous to https://github.com/jenkinsci/groovy-sandbox/pull/55 but picking up https://github.com/cloudbees/cloudbees-oss-parent/pull/6. @abayer @dwnusbaum @daniel-beck
> com.cloudbees:cloudbees-oss-parent:9

- doc/sandbox.md
It looks like maybe markdown changed since this was written. I added a space after # so the text was made into a header.
I didn't change the last line. I'm not sure why it shows a diff.
> Update to headers

- lib/src/main/java/com/cloudbees/groovy/cps/CpsTransformer.java
- lib/src/test/groovy/com/cloudbees/groovy/cps/CpsTransformerTest.groovy
Better error messages are generally better things to have.
> Switch to compilation errors when reasonable.

- lib/src/main/java/com/cloudbees/groovy/cps/sandbox/DefaultInvoker.java
- lib/src/test/groovy/com/cloudbees/groovy/cps/CpsTransformerTest.groovy
…SuperClass()
See [JENKINS-52395](https://issues.jenkins-ci.org/browse/JENKINS-52395).
> [FIXED JENKINS-52395] Use the super class of methodType as the invoking class (sender) of the method on the object (receiver)
