cloudbees/groovy-cps

pom.xml
src/main/java/com/cloudbees/groovy/cps/impl/Caller.java

Found that `Caller.Info` can be holding onto script classes even after the script has finished. @reviewbybees esp. @kohsuke

Memory leak

---

src/main/java/com/cloudbees/groovy/cps/impl/Caller.java
src/test/java/com/cloudbees/groovy/cps/impl/CallerTest.java

Fixes regression in #2:
```
java.lang.NullPointerException
at com.cloudbees.groovy.cps.impl.Caller.isAsynchronous(Caller.java:50)
at com.cloudbees.groovy.cps.impl.Caller$isAsynchronous.call(Unknown Source)
at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.each(CpsDefaultGroovyMethods.groovy:24)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at org.codehaus.groovy.runtime.metaclass.ReflectionMetaMethod.invoke(ReflectionMetaMethod.java:51)
at org.codehaus.groovy.runtime.metaclass.NewInstanceMetaMethod.invoke(NewInstanceMetaMethod.java:54)
at …
```

Null check for synchronous calls

---

src/main/groovy/com/cloudbees/groovy/cps/CpsTransformer.groovy
src/main/java/com/cloudbees/groovy/cps/Builder.java
src/main/java/com/cloudbees/groovy/cps/TransformerConfiguration.java
src/main/java/com/cloudbees/groovy/cps/impl/ClosureBlock.java

Allow the calling code to use a subtype of `CpsClosure` to customize the behaviour of closure.
This was necessary for Jenkins Workflow plugin to intercept the sleep()
call, which requires adding a declared method on CpsClosure.
See more about this in jenkinsci/workflow-plugin #131.
In anticipation of additional CPS transformer configuration switches in
the future, this change introduces a class that collects such random
switches.

Added a hook to insert a subtype of CpsClosure.

---

src/main/java/com/cloudbees/groovy/cps/impl/AssertBlock.java
src/main/java/com/cloudbees/groovy/cps/impl/ContinuationGroup.java
src/main/java/com/cloudbees/groovy/cps/impl/DoWhileBlock.java
src/main/java/com/cloudbees/groovy/cps/impl/ElvisBlock.java
src/main/java/com/cloudbees/groovy/cps/impl/ForLoopBlock.java
src/main/java/com/cloudbees/groovy/cps/impl/IfBlock.java
src/main/java/com/cloudbees/groovy/cps/impl/LogicalOpBlock.java
src/main/java/com/cloudbees/groovy/cps/impl/WhileBlock.java
src/test/groovy/com/cloudbees/groovy/cps/CpsTransformerTest.groovy

Note that the test does not fail without the main source patch, for reasons unknown, though it does print the stack trace
```
java.lang.NullPointerException
at com.cloudbees.groovy.cps.impl.ContinuationGroup.asBoolean(ContinuationGroup.java:50)
at com.cloudbees.groovy.cps.impl.ElvisBlock$ContinuationImpl.jump(ElvisBlock.java:36)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
at com.cloudbees.groovy.cps.impl.LocalVariableBlock$LocalVariable.get(LocalVariableBl …
```

ContinuationGroup.asBoolean did not correctly implement Groovy truthiness

---

pom.xml
src/main/groovy/com/cloudbees/groovy/cps/CpsTransformer.groovy
src/test/groovy/com/cloudbees/groovy/cps/CpsTransformerTest.groovy

[JENKINS-32062](https://issues.jenkins-ci.org/browse/JENKINS-32062)
@reviewbybees esp. @kohsuke

[JENKINS-32062] Arrays could not be passed directly to methods

---

src/main/java/com/cloudbees/groovy/cps/impl/ContinuationGroup.java
src/main/java/com/cloudbees/groovy/cps/impl/DGMPatcher.java
src/test/groovy/com/cloudbees/groovy/cps/CpsTransformerTest.groovy

Hey @jglick, I delivered on my next airplane project.
See `DGMPatcher` class javadoc for the explanation of the approach. Compare to #11, this handles every subtype of `List`, not just `ArrayList`, no matter what state Groovy is in by the time this code runs.
Once this approach is blessed, we still need to fill in `CpsDefaultGroovyMethods` with all the replacements that we need, and there are hundreds.
@reviewbybees, in particular @jglick

Handle Object.each { ... }

---

README.md
doc/sandbox.md
src/main/groovy/com/cloudbees/groovy/cps/CpsTransformer.groovy
src/main/groovy/com/cloudbees/groovy/cps/SandboxCpsTransformer.groovy
src/main/java/com/cloudbees/groovy/cps/Builder.java
src/main/java/com/cloudbees/groovy/cps/Env.java
src/main/java/com/cloudbees/groovy/cps/impl/ArrayAccessBlock.java
src/main/java/com/cloudbees/groovy/cps/impl/AssignmentBlock.java
src/main/java/com/cloudbees/groovy/cps/impl/AttributeAccessBlock.java
src/main/java/com/cloudbees/groovy/cps/impl/CallSiteBlock.java
src/main/java/com/cloudbees/groovy/cps/impl/CallSiteBlockSupport.java
src/main/java/com/cloudbees/groovy/cps/impl/ContinuationGroup.java
src/main/java/com/cloudbees/groovy/cps/impl/ExcrementOperatorBlock.java
src/main/java/com/cloudbees/groovy/cps/impl/FunctionCallBlock.java
src/main/java/com/cloudbees/groovy/cps/impl/PropertyAccessBlock.java
src/main/java/com/cloudbees/groovy/cps/impl/PropertyishBlock.java
src/main/java/com/cloudbees/groovy/cps/impl/package-info.java
src/main/java/com/cloudbees/groovy/cps/sandbox/CallSiteTag.java
src/main/java/com/cloudbees/groovy/cps/sandbox/DefaultInvoker.java
src/main/java/com/cloudbees/groovy/cps/sandbox/Invoker.java
src/main/java/com/cloudbees/groovy/cps/sandbox/SandboxInvoker.java
src/main/java/com/cloudbees/groovy/cps/sandbox/Trusted.java
src/main/java/com/cloudbees/groovy/cps/sandbox/Untrusted.java
src/test/groovy/com/cloudbees/groovy/cps/sandbox/SandboxInvokerTest.groovy

See `doc/sandbox.md` for the explanation of what this does.
@reviewbybees

Mixing trusted & untrusted code in one CPS session

---

src/main/java/com/cloudbees/groovy/cps/impl/ContinuationGroup.java
src/test/groovy/com/cloudbees/groovy/cps/CpsTransformerTest.groovy

Until #24 is finished, the trunk versions of this component (including the 1.7 and 1.8 releases) do not work in Groovy 2 and hence Jenkins 2. So basically suppress #23 for now. With this merged and a 1.9 cut, we should be able to release https://github.com/jenkinsci/workflow-cps-plugin/pull/33.
@reviewbybees esp. @kohsuke

[JENKINS-34064] DGMPatcher is broken in Groovy 2, so do not try to use it at all

---

src/main/groovy/com/cloudbees/groovy/cps/CpsTransformer.groovy
src/main/java/com/cloudbees/groovy/cps/Builder.java
src/main/java/com/cloudbees/groovy/cps/Env.java
src/main/java/com/cloudbees/groovy/cps/impl/BlockScopeEnv.java
src/main/java/com/cloudbees/groovy/cps/impl/CallEnv.java
src/main/java/com/cloudbees/groovy/cps/impl/ClosureCallEnv.java
src/main/java/com/cloudbees/groovy/cps/impl/FunctionCallEnv.java
src/main/java/com/cloudbees/groovy/cps/impl/LocalVariableBlock.java
src/main/java/com/cloudbees/groovy/cps/impl/ProxyEnv.java
src/test/groovy/com/cloudbees/groovy/cps/CpsTransformerTest.groovy

Fixes #31. Builds on top of https://github.com/cloudbees/groovy-cps/pull/32 by adding support for type-checked list constructors.  Uses the Groovy internal method to do type coercion before storage, and Envs store variable types when the variables are declared.
TODO:
This should provide the basic implementation and cover main cases.  If there are special cases that need additional work to support, those can be later efforts.

Fixes #31: Constructor coercion support

---

src/main/groovy/com/cloudbees/groovy/cps/CpsTransformer.groovy
src/test/groovy/com/cloudbees/groovy/cps/CpsTransformerTest.groovy

This fix marks abstract methods as nonTransformable

Fixes #42: Compilation threw NPE on abstract methods

---

src/test/groovy/com/cloudbees/groovy/cps/CpsTransformerTest.groovy

#15
Marked as `@NotYetImplemented` since there is no fix yet
There is an extra assertion to assert for the datatype because of
assertion report lacking that information (the `java.io.StringWriter`
instance is displayed according to its `toString()` representation) which
does not suit the current test where we compare with `java.lang.String`

Unit test for GString with StringWriter closure

---

src/test/groovy/com/cloudbees/groovy/cps/CpsTransformerTest.groovy

Unit test for #28 
Marked as `@NotYetImplemented` as there is no fix yet
rehydrate needed when integrating OOP design in DSL scripts

Unit test for Closure.rehydrate()

---

src/main/groovy/com/cloudbees/groovy/cps/CpsTransformer.groovy

[GROOVY-6263](https://issues.apache.org/jira/browse/GROOVY-6263) breaks `SandboxCpsTransformer` in Groovy prior to 2.5, i.e., all versions used by current Jenkins releases.
@reviewbybees

[GROOVY-6263] Removing private methods so we can use categories

---

lib/src/main/java/com/cloudbees/groovy/cps/impl/ClosureCallEnv.java
lib/src/main/java/com/cloudbees/groovy/cps/impl/CpsCallable.java
lib/src/test/groovy/com/cloudbees/groovy/cps/CpsTransformerTest.groovy

[JENKINS-38268](https://issues.jenkins-ci.org/browse/JENKINS-38268)
Previously, any variables that hadn't been explicitly declared (via
`ClosureCallEnv.declareVariable`) in a `Closure` would end up getting
set in the captured `Env`. Which means we'd end up setting things
globally when we really didn't mean to. This changes that to only set
a variable in the captured `Env` if there's no `locals` variable
defined by that name *and* the captured `Env` has a non-null return
for `getVariableType(name)` - i.e., the variable name has already been
declared in the captured `Env`.
Further tests in a `parallel` will be needed in `workflow-cps`.

[FIXED JENKINS-38268] Proper lexical scoping for closure variables.

---

dgm-builder/src/main/java/com/cloudbees/groovy/cps/tool/Translator.java

#60 stripped down to its essentials.
How I got here: I was worried that #60 would open a security vulnerability, specifically calls from `CpsDefaultGroovyMethods` (or its delegates) to user-defined methods that did not happen to be some `Closure.call` overload. So I hit on `Iterable.iterator`, which is also called on user-controlled arguments but for which we do not do the check. There was a snag that `IteratorHack` actually ignores _any_ override of this method, but even with that suppressed, the test did not fail the way I expected:
```diff
diff --git a/src/main/java/org/jenkinsci/plugins/workflow/cps/persistence/IteratorHack.java b/src/main/java/org/jenkinsci/plugins/workflow/cps/persistence/IteratorHack.java
index 06f7dbe1..1e119c30 100644
--- …
```

Use trusted builder for translation

---

lib/pom.xml
pom.xml

I'm working on tooling to do testing of core + groovy-sandbox +
groovy-cps + workflow-cps + script-security + the rest of the main
Pipeline plugins against bleeding-edge versions of each other and
different versions of Groovy. To do this, it'd be a lot easier if the
dependencies between the various things I'm building/testing had their
versions controlled by properties.

Add groovy-sandbox.version POM property

---

lib/src/main/java/com/cloudbees/groovy/cps/impl/CpsCallableInvocation.java

Just wastes time computing a stack trace for a throwable we intend to catch without logging.
(One approach to [JENKINS-31314](https://issues.jenkins-ci.org/browse/JENKINS-31314) might use the stack trace, but even then I think not.)
@reviewbybees

Do nothing in CpsCallableInvocation.fillInStackTrace

---

lib/src/main/java/com/cloudbees/groovy/cps/Envs.java
lib/src/main/java/com/cloudbees/groovy/cps/impl/BlockScopeEnv.java
lib/src/main/java/com/cloudbees/groovy/cps/impl/CallEnv.java
lib/src/main/java/com/cloudbees/groovy/cps/impl/ClosureCallEnv.java
lib/src/main/java/com/cloudbees/groovy/cps/impl/CpsClosureDef.java
lib/src/main/java/com/cloudbees/groovy/cps/impl/CpsFunction.java
lib/src/main/java/com/cloudbees/groovy/cps/impl/ForInLoopBlock.java
lib/src/main/java/com/cloudbees/groovy/cps/impl/FunctionCallEnv.java
lib/src/main/java/com/cloudbees/groovy/cps/impl/LoopBlockScopeEnv.java
lib/src/main/java/com/cloudbees/groovy/cps/impl/TryBlockEnv.java
lib/src/main/java/com/cloudbees/groovy/cps/impl/TryCatchBlock.java

Provides a solution for #73 by lazily initializing the Maps for scoped environments, and starting them out sized for quite small arrays of locals since often blocks will be empty or have few variables. 
Why does this matter?  See the linked issue for jmap histogram of a real user who has quite a bit of memory consumed by HashMaps from these classes (in fact they're the third largest memory consumer there, even before their contents!). 
This should also reduce GC costs of pipeline rather significantly because the number of objects we create will be quite a bit smaller.
Included in https://github.com/jenkinsci/workflow-cps-plugin/pull/176 to run tests using this.

Reduce memory of CPS code significantly by lazily initializing locals maps

---

dgm-builder/src/main/java/com/cloudbees/groovy/cps/tool/Translator.java
lib/src/main/java/com/cloudbees/groovy/cps/impl/CpsBooleanClosureWrapper.java

[JENKINS-47071](https://issues.jenkins-ci.org/browse/JENKINS-47071)
BooleanClosureWrapper isn't serializable, so attempts to serialize it
(i.e., saveProgram) result in errors. This replaces
BooleanClosureWrapper with CpsBooleanClosureWrapper, which *is*
serializable.
No point in testing here, but actual test coming downstream.

[FIXED JENKINS-47071] Replace BooleanClosureWrapper with serializable

---

lib/src/main/java/com/cloudbees/groovy/cps/CpsTransformer.java
lib/src/test/groovy/com/cloudbees/groovy/cps/CpsTransformerTest.groovy

[JENKINS-47363](https://issues.jenkins-ci.org/browse/JENKINS-47363)
This is probably better than #78 - that works around the problem, but
in a fairly hackish way, while this instead accepts the limitation and
gives a meaningful error message when a list expression is >250
elements or a map expression is >125 entries.

[JENKINS-47363] Meaningful errors for oversized map/list expressions

---

lib/src/main/java/com/cloudbees/groovy/cps/CpsTransformer.java
lib/src/test/groovy/com/cloudbees/groovy/cps/sandbox/SandboxInvokerTest.groovy

Finally tracked down a silly bug that was resulting in gratuitous `Checker.checkedStaticCall` invocations:
```groovy
private static final CpsFunction __cps__123 = __cps__123();
//                                            ^^^^^^^^^^^^
```
@reviewbybees

Do not run the sandbox transformer on field initializers created by the CPS transformer

---

lib/src/main/java/com/cloudbees/groovy/cps/CpsTransformer.java
lib/src/main/java/com/cloudbees/groovy/cps/SandboxCpsTransformer.java
lib/src/test/groovy/com/cloudbees/groovy/cps/sandbox/SandboxInvokerTest.groovy

[JENKINS-45575](https://issues.jenkins-ci.org/browse/JENKINS-45575)
Turns out JENKINS-45575 is because I added proper support for multiple assignment in non-sandbox but not in sandbox. Oops.
Also get rid of `SandboxCpsTransformer#visitDeclarationExpression` by switching to overridden methods for getting the value for both single and multiple assignments that do the `SandboxTransformer#mightBePositionalArgumentConstructor` logic directly.

[FIXED JENKINS-45575] Add support for multiple assignment in sandbox

---

lib/src/main/java/com/cloudbees/groovy/cps/CpsTransformer.java

[JENKINS-26313](https://issues.jenkins-ci.org/browse/JENKINS-26313)
Note for myself and others in the future so we know why JENKINS-26313 is a won't fix and why we don't transform constructors.

[JENKINS-26313] Add javadoc explaining why constructors can't be transformed

---

lib/pom.xml
lib/src/main/java/com/cloudbees/groovy/cps/sandbox/DefaultInvoker.java
lib/src/test/groovy/com/cloudbees/groovy/cps/CpsTransformerTest.groovy
lib/src/test/groovy/com/cloudbees/groovy/cps/sandbox/SandboxInvokerTest.groovy

[JENKINS-45982](https://issues.jenkins-ci.org/browse/JENKINS-45982)
Initially just a test reproducing the issue described in JENKINS-45982 - specifically, that calling a `super` method when the `super` class is also CPS-transformed fails, due to a `CpsCallableInvocation` ending up in the way. Will grow this as I make progress towards a fix.

[JENKINS-45982] Calls to CPS-transformed super methods fail

---

lib/src/test/groovy/com/cloudbees/groovy/cps/CpsTransformerTest.groovy

See [JENKINS-31484](https://issues.jenkins-ci.org/browse/JENKINS-31484).
This PR adds an ignored test for another variant of that issue that works in regular Groovy but not in groovy-cps.

[JENKINS-31484] Add ignored test for unfixed variant of JENKINS-31484

---

lib/src/main/java/com/cloudbees/groovy/cps/CpsTransformer.java
lib/src/main/java/com/cloudbees/groovy/cps/MethodLocation.java

[JENKINS-57085](https://issues.jenkins-ci.org/browse/JENKINS-57085), in part a workaround for https://github.com/x-stream/xstream/pull/145, but also an analogue of https://github.com/apache/groovy/commit/7662296e5c2679d350f48d6d6f104d15c6f3c00d.

[JENKINS-57085] Avoid complex StackTraceElement.fileName values

---

lib/src/main/java/com/cloudbees/groovy/cps/impl/CpsCallableInvocation.java

Hey, thought i'd take a stab at implementing the fix for the pull requests against https://github.com/jenkinsci/workflow-cps-plugin/pull/305 and https://github.com/jenkinsci/workflow-cps-plugin/pull/306.
Just trying to lend a helping hand!  The unit tests added in the workflow-cps-plugin that are failing due to the false positives are passing with this change.

[JENKINS-58501] add exceptions for metaprogramming to CPS mismatches

---

lib/src/main/java/com/cloudbees/groovy/cps/impl/ContinuationGroup.java

Tests placed into jenkinsci/workflow-cps-plugin#315

JENKINS-58620 GroovyShell.evaluate should be skipped in the mismatch handler

---

lib/src/main/java/com/cloudbees/groovy/cps/impl/CpsCallableInvocation.java

[JENKINS-58407](https://issues.jenkins-ci.org/browse/JENKINS-58407)
Don't throw a mismatch for cases like `foo.someField()` where `foo` is
either an `Object` with a field `someField` that's a closure, or a
`Map` with a `Closure` value for the key `someField`.
https://github.com/jenkinsci/workflow-cps-plugin/pull/316

[FIXED JENKINS-58407] Treat closure fields and map values properly

---

lib/src/main/java/com/cloudbees/groovy/cps/CpsTransformer.java
lib/src/test/groovy/com/cloudbees/groovy/cps/AbstractGroovyCpsTest.groovy
lib/src/test/java/com/cloudbees/groovy/cps/CpsTransformer2Test.java

See [JENKINS-57253](https://issues.jenkins-ci.org/browse/JENKINS-57253) and https://github.com/jenkinsci/workflow-cps-plugin/pull/356 (CC @basil).
Makes improper use of `break` or `continue` statements fail during compilation with the same error messages as Groovy itself instead of at runtime with a CPS-specific error message.
`LabelVerifier` normally runs during `CompilePhase.CLASS_GENERATION`, but CPS transformation runs earlier during `CompilePhase.CANONICALIZATION` and obliterates the original control-flow statements that `LabelVerifier` would check, so the `LabelVerifier` that runs during `CompilePhase.CLASS_GENERATION` can only catch issues in groovy-cps itself. 
To be able to catch errors in the user's program, this PR makes `CPSTransformer` run `LabelVerifier` manually prior to …

[JENKINS-57253] Verify correct usage of break and continue statements during compilation
